app/flask_app/squeaky_puppy/controllers.py
from flask import Blueprint, render_template, Response, request
from sqlalchemy import select, join, func, delete
from forms import *
import json
from datetime import datetime
from app import config

squeaky_puppy = Blueprint(
    'squeaky_puppy',
    __name__,
)


@squeaky_puppy.route('/')
def home():
    the_form = MyForm()
    user_form = UserForm()
    assessment_form = AssessmentForm()
    blacklist_form = BlacklistForm()
    callback_form = CallbackForm()
    return render_template(
        'base.html',
        form=the_form,
        user_form=user_form,
        assessment_form=assessment_form,
        blacklist_form=blacklist_form,
        callback_form=callback_form,
    )


@squeaky_puppy.route('/callback', methods=['GET', 'POST', 'DELETE'])
@squeaky_puppy.route('/callback/<string:cb_id>', methods=['GET', 'POST', 'DELETE'])
def callback(cb_id=None):
    if request.method == 'GET':
        callback_form = CallbackForm()

        results = select([
            config.CALLBACK_TABLE.c.id,
            config.CALLBACK_TABLE.c.callback,
            func.count(
                config.HIT_TABLE.c.callback_id
            ),
        ]).select_from(
            config.CALLBACK_TABLE.outerjoin(
                config.HIT_TABLE,
                config.CALLBACK_TABLE.c.id == config.HIT_TABLE.c.callback_id
            )
        ).group_by(
            config.CALLBACK_TABLE.c.id
        ).execute().fetchall()

        callbacks = []

        for result in results:
            callbacks.append({
                'id': result.id,
                'name': result.callback,
                'hits': result[2],
            })

        return render_template(
            'callbacks.html',
            callback_form=callback_form,
            callbacks=callbacks,
        )
    elif request.method == 'DELETE':
        try:
            config.HIT_TABLE.delete(
                config.HIT_TABLE.c.callback_id == cb_id
            ).execute()
            config.CALLBACK_TABLE.delete(
                config.CALLBACK_TABLE.c.id == cb_id
            ).execute()
        except Exception as e:
            return Response(json.dumps({'success': False, 'error': str(e)}), mimetype='application/json'), 500
        return Response(json.dumps({'success': True}), mimetype='application/json')
    elif request.method == 'POST':
        # new
        callback_form = CallbackForm(obj=request.data)
        if not callback_form.validate():
            return 'Bad data', 400
        config.CALLBACK_TABLE.insert(dict(request.form)).execute()
        return Response(json.dumps({'success': True}), mimetype='application/json')


@squeaky_puppy.route('/user', methods=['GET', 'POST', 'DELETE'])
@squeaky_puppy.route('/user/<string:user_id>', methods=['GET', 'POST', 'DELETE'])
def user(user_id=None):
    if request.method == 'GET':
        if not user_id:
            user_form = UserForm()

            results = select([
                config.USER_TABLE.c.id,
                config.USER_TABLE.c.name,
                config.USER_TABLE.c.email,
                config.ASSESSMENT_TABLE.c.name.label('assessment'),
            ]).select_from(
                config.USER_TABLE.join(
                    config.NOTIFY_TABLE,
                    config.NOTIFY_TABLE.c.user_id == config.USER_TABLE.c.id
                ).join(
                    config.ASSESSMENT_TABLE,
                    config.ASSESSMENT_TABLE.c.id == config.NOTIFY_TABLE.c.assessment_id
                )
            ).execute().fetchall()

            users = []
            user_mapping = {}

            for result in results:
                if result.id not in user_mapping:
                    user_mapping[result.id] = len(users)
                    users.append({
                        'id': result.id,
                        'name': result.name,
                        'email': result.email,
                        'assessments': [],
                    })
                users[user_mapping[result.id]]['assessments'].append(result.assessment)

            return render_template(
                'users.html',
                user_form=user_form,
                users=users,
            )
        else:
            user_data = select([
                config.USER_TABLE,
            ]).where(
                config.USER_TABLE.c.id == user_id
            ).execute().fetchone()
            edit_user_form = EditUserForm(obj=user_data)
            return render_template(
                'edit_user.html',
                edit_user_form=edit_user_form,
            )
    elif request.method == 'POST':
        # update
        user_form = UserForm(obj=request.data)
        if not user_form.validate():
            return 'Bad data', 400
        if not request.form['id']:
            config.USER_TABLE.insert(dict(request.form)).execute()
        else:
            config.USER_TABLE.update(config.USER_TABLE.c.id == request.form['id'], dict(request.form)).execute()
        return Response(json.dumps({'success': True}), mimetype='application/json')
    elif request.method == 'DELETE':
        try:
            config.USER_TABLE.delete(
                config.USER_TABLE.c.id == user_id
            ).execute()
        except Exception as e:
            return Response(json.dumps({'success': False, 'error': str(e)}), mimetype='application/json'), 500
        return Response(json.dumps({'success': True}), mimetype='application/json')


@squeaky_puppy.route('/assessment', methods=['GET', 'POST', 'DELETE'])
@squeaky_puppy.route('/assessment/<string:assessment_id>', methods=['GET', 'POST', 'DELETE'])
def assessment(assessment_id=None):
    if request.method == 'GET':
        if not assessment_id:
            assessment_form = AssessmentForm()

            results = select([
                config.ASSESSMENT_TABLE.c.id,
                config.ASSESSMENT_TABLE.c.name,
                config.ASSESSMENT_TABLE.c.date_started,
            ]).execute().fetchall()

            assessments = []

            for result in results:
                hits = len(select([
                    config.HIT_TABLE.c.id,
                ]).where(
                    config.HIT_TABLE.c.assessment_id == result.id
                ).execute().fetchall())

                users = select([
                    config.USER_TABLE.c.name,
                ]).select_from(
                    config.ASSESSMENT_TABLE.join(
                        config.NOTIFY_TABLE,
                        config.NOTIFY_TABLE.c.assessment_id == config.ASSESSMENT_TABLE.c.id,
                    ).join(
                        config.USER_TABLE,
                        config.USER_TABLE.c.id == config.NOTIFY_TABLE.c.user_id
                    )
                ).where(
                    config.NOTIFY_TABLE.c.assessment_id == result.id
                ).execute().fetchall()
                # delete all the data (jk)

                assessments.append({
                    'id': result.id,
                    'name': result.name,
                    'date_started': result.date_started,
                    'hits': hits,
                    'users': users,
                })

            return render_template(
                'assessments.html',
                assessment_form=assessment_form,
                assessments=assessments,
            )
        else:
            assessment_data = select([
                config.ASSESSMENT_TABLE,
            ]).where(
                config.ASSESSMENT_TABLE.c.id == assessment_id
            ).execute().fetchone()
            assignee_data = select([
                config.NOTIFY_TABLE,
            ]).where(
                config.NOTIFY_TABLE.c.assessment_id == assessment_id
            ).execute().fetchall()
            full_data = {
                'name': assessment_data['name'],
                'assignees': [],
                'id': assessment_id,
            }
            for assignee in assignee_data:
                full_data['assignees'].append(assignee['user_id'])
            edit_assessment_form = EditAssessmentForm(obj=Struct(**full_data))
            return render_template(
                'edit_assessment.html',
                edit_assessment_form=edit_assessment_form,
            )
    elif request.method == 'POST':
        # update / create
        # delete all the data
        assessment_form = AssessmentForm(obj=request.data)
        if not assessment_form.validate():
            return 'Bad data', 400
        if not assessment_id:
            now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            assessment_id = config.ASSESSMENT_TABLE.insert({
                'name': request.form['name'],
                'date_started': now,
            }).execute().inserted_primary_key[0]

            for assignee in request.form.getlist('assignees'):
                config.NOTIFY_TABLE.insert({
                    'assessment_id': assessment_id,
                    'user_id': assignee,
                }).execute()
        else:
            config.ASSESSMENT_TABLE.update(
                config.ASSESSMENT_TABLE.c.id == assessment_id,
                {'name': request.form['name']}
            ).execute()
            config.NOTIFY_TABLE.delete(
                config.NOTIFY_TABLE.c.assessment_id == assessment_id
            ).execute()
            for assignee in request.form.getlist('assignees'):
                config.NOTIFY_TABLE.insert({
                    'assessment_id': assessment_id,
                    'user_id': assignee,
                }).execute()
        return Response(json.dumps({'success': True}), mimetype='application/json')
    elif request.method == 'DELETE':
        try:
            config.HIT_TABLE.delete(
                config.HIT_TABLE.c.assessment_id == assessment_id
            ).execute()
            config.NOTIFY_TABLE.delete(
                config.NOTIFY_TABLE.c.assessment_id == assessment_id
            ).execute()
            config.ASSESSMENT_TABLE.delete(

app/flask_app/templates/_formhelper.html
{%- macro render_form(form, form_id) %}
<form class="ui form" id="{{ form_id }}">
    {%- for field in form %}
        {{ render_field(field) }}
    {% endfor -%}
    <div class="ui error message"></div>
</form>
{% endmacro -%}

{%- macro render_field(field) %}
    <div class="field">
        {% if field.type != "HiddenField" %}
            {{ field.label }}
        {% endif %}
        {% if field.type == "SelectMultipleField" %}
            {{ field(class_="ui fluid search dropdown") }}
        {% else %}
            {{ field }}
        {% endif %}
    </div>
{% endmacro -%}

{%- set success_header -%}
    <div class="ui positive message"><i class="close icon"></i><div class="header">
{%- endset -%}
{%- set error_header -%}
    <div class="ui negative message"><i class="close icon"></i><div class="header">
{%- endset -%}
{%- set title_content -%}
    </div><p>
{%- endset -%}
{%- set footer -%}
    </p></div>
{%- endset -%}

app/flask_app/templates/assessments.html
{%- from "_formhelper.html" import render_form, success_header, error_header, title_content, footer -%}
<button class="ui basic button assessments">
    <i class="icon add circle"></i>
    New assessment
</button>
<table class="ui celled table">
<thead>
    <tr>
    <th>Name</th>
    <th>Hits</th>
    <th>Users</th>
    </tr>
</thead>
<tbody>
    {%- for row in assessments -%}
        <tr>
            <td>
                <i class="icon link trash delete_assessment" data-id="{{ row['id'] }}"></i>
                <i class="icon link edit edit_assessment" data-id="{{ row['id'] }}"></i>
                {{ row['name'] }}
            </td>
            <td>
                {{ row['hits'] }}
                <i class="icon link search view_assessment" data-id="{{ row['id'] }}"></i>
            </td>
            <td>
                <div class="ui horizontal divided list">
                {% for user in row['users'] %}
                    <div class="item">
                    {{ user[0] }}
                    </div>
                {% endfor %}
                </div>
            </td>
        </tr>
    {%- endfor -%}
</tbody>
</table>

<script>
    $(function () {
        $('.ui.dropdown').dropdown();
        $('.ui.modal.assessments').modal({
            onApprove : function() {
                return false;
            }
        }).modal('attach events', '.button.assessments', 'show');

        $('#create_assessment').form({
            fields: {
                name      : 'empty',
                assignees : ['minCount[1]', 'empty'],
            }
        });

        $('#create_assessment').api({
            action: 'create assessment',
            method: 'POST',
            serializeForm: true,
            onSuccess: function() {
                $('#create_assessment').trigger('reset');
                $('.ui.dropdown').dropdown('clear');
                $('.ui.modal.assessments').modal('hide');
                $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Assessment created!{{ footer|safe }}');
                $('#tab_assessments').click()
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
            onError: function() {
                return false;
            },
        });

        $('.delete_assessment').api({
            action: 'delete assessment',
            method: 'DELETE',
            serializeForm: true,
            onSuccess: function() {
                $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Assessment deleted!{{ footer|safe }}');
                $('#tab_assessments').click()
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
            onError: function(errorMessage) {
                $('div.a_message').html('{{ error_header|safe }} Error{{ title_content|safe }}' + errorMessage + '{{ footer|safe }}');
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
        });

        $('.edit_assessment').api({
            action: 'modify assessment',
            method : 'GET',
            dataType: 'html',
            stateContext : '#edit_assessment_container',
            onSuccess: function(response) {
                $('.ui.modal.edit_assessment').html("");
                $('#edit_assessment_container').html(response);
                $('.ui.dropdown').dropdown();
                $('#edit_assessment_modal').modal({
                    onApprove : function() {
                        return false;
                    },
                }).modal('show');
                $('#edit_assessment').api({
                    action: 'modify assessment',
                    method: 'POST',
                    serializeForm: true,
                    onSuccess: function() {
                        $('.ui.modal.edit_assessment').modal('hide');
                        $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Assessment updated!{{ footer|safe }}');
                        $('#tab_assessments').click()
                        $('.message .close').on('click', function() {
                            $(this).closest('.message').transition('fade');
                        });
                    },
                    onError: function() {
                        return false;
                    },
                    urlData: {
                        id:  $('#id').val()
                    },
                });
            },
        });

        $('.view_assessment').api({
            action: 'view assessment',
            method : 'GET',
            dataType: 'html',
            stateContext : '#view_assessment_container',
            onSuccess: function(response) {
                $('.ui.modal.view_assessment').html("");
                $('#view_assessment_container').html(response);
                $('.ui.dropdown').dropdown();
                $('#view_assessment_modal').modal({
                    onApprove : function() {
                        return false;
                    },
                }).modal('show');
            },
        });
    });
</script>

<div class="ui modal assessments">
    <div class="header">
        Create new Assessment
    </div>
    <div class="content">
        <p>
            {{ render_form(assessment_form, "create_assessment") }}
        </p>
    </div>
    <div class="actions">
        <input type="submit" value="Create" form="create_assessment" class="ui positive button" id="btn_create_assessment" formmethod="post">
        <div class="ui button cancel">Cancel</div>
    </div>
</div>

<div id="edit_assessment_container"></div>
<div id="view_assessment_container"></div>

app/flask_app/templates/base.html
<!DOCTYPE html>
{%- from "_formhelper.html" import render_form -%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="{{ url_for('static', filename='js/jquery-3.1.0.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tablesort.js') }}"></script>
    <script src="{{ url_for('static', filename='js/semantic.min.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/semantic.min.css') }}">
</head>
<body>
<div class="ui secondary pointing menu">
    <a class="item active" data-tab="tab_home">
        Home
    </a>
    <a class="item" id ="tab_callbacks" data-tab="tab_callbacks">
        Callbacks
    </a>
    <a class="item" id="tab_users" data-tab="tab_users">
        Users
    </a>
    <a class="item" id="tab_assessments" data-tab="tab_assessments">
        Assessments
    </a>
    <a class="item" id="tab_blacklist" data-tab="tab_blacklist">
        Domain Blacklist
    </a>
    <a class="item" data-tab="tab_log">
        Log
    </a>
    <a class="item" data-tab="tab_config">
        Config
    </a>
    <div class="right menu">
        <a class="ui item">
            Logout
        </a>
    </div>
</div>
<div class="a_message"></div>
&nbsp;
<div class="ui tab active" data-tab="tab_home">
    a
</div>
<div class="ui tab" id="tab_callbacks_content" data-tab="tab_callbacks">
</div>
<div class="ui tab" id="tab_users_content" data-tab="tab_users">
</div>
<div class="ui tab" id="tab_assessments_content" data-tab="tab_assessments">
</div>
<div class="ui tab" id="tab_blacklist_content" data-tab="tab_blacklist">
</div>
<div class="ui tab" data-tab="tab_log">
    f
</div>
<div class="ui tab" data-tab="tab_config">
    {% include "config.html" %}
</div>




<script>
    $(function () {
        $('.menu .item').tab();
        $.fn.api.settings.api = {
            'get callbacks'      : '{{ url_for("squeaky_puppy.callback") }}',
            'create callback'    : '{{ url_for("squeaky_puppy.callback") }}',
            'delete callback'    : '{{ url_for("squeaky_puppy.callback") }}/{id}',
            'get users'          : '{{ url_for("squeaky_puppy.user") }}',
            'create user'        : '{{ url_for("squeaky_puppy.user") }}',
            'modify user'        : '{{ url_for("squeaky_puppy.user") }}/{id}',
            'delete user'        : '{{ url_for("squeaky_puppy.user") }}/{id}',
            'get assessments'    : '{{ url_for("squeaky_puppy.assessment") }}',
            'create assessment' : '{{ url_for("squeaky_puppy.assessment") }}',
            'modify assessment' : '{{ url_for("squeaky_puppy.assessment") }}/{id}',
            'delete assessment' : '{{ url_for("squeaky_puppy.assessment") }}/{id}',
            'view assessment'   : '{{ url_for("squeaky_puppy.view_assessment") }}/{id}',
            'get blacklist'     : '{{ url_for("squeaky_puppy.domain") }}',
            'create blacklist'     : '{{ url_for("squeaky_puppy.domain") }}',
            'delete blacklist'     : '{{ url_for("squeaky_puppy.domain") }}/{id}',
        };

        $('#tab_callbacks').api({
            action: 'get callbacks',
            method : 'GET',
            dataType: 'html',
            stateContext : '#tab_callbacks_content',
            onSuccess: function(response) {
                $('#tab_callbacks_content').html(response);
                $('table').tablesort()
            },
        });

        $('#tab_users').api({
            action: 'get users',
            method : 'GET',
            dataType: 'html',
            stateContext : '#tab_users_content',
            onSuccess: function(response) {
                $('#tab_users_content').html(response);
                $('table').tablesort()
            },
        });

        $('#tab_assessments').api({
            action: 'get assessments',
            method : 'GET',
            dataType: 'html',
            stateContext : '#tab_assessments_content',
            onSuccess: function(response) {
                $('#tab_assessments_content').html(response);
                $('table').tablesort()
            },
        });

        $('#tab_blacklist').api({
            action: 'get blacklist',
            method : 'GET',
            dataType: 'html',
            stateContext : '#tab_blacklist_content',
            onSuccess: function(response) {
                $('#tab_blacklist_content').html(response);
                $('table').tablesort()
            },
        });

        $('.ui.dropdown').dropdown();
    });
</script>
</body>
</html>

app/flask_app/templates/blacklist.html
{%- from "_formhelper.html" import render_form, success_header, error_header, title_content, footer -%}
<div class="ui grid">
    <div class="row">
        <button class="ui basic button blacklists">
            <i class="world icon"></i>
            Blacklist domain
        </button>
    </div>
    <div class=" row"><div class="four wide column">
        <div class="ui celled list">
            {%- for domain in domains -%}
            <div class="item">
                <i class="icon link trash delete_domain" data-id="{{ domain['id'] }}"></i>
                <div class="content">
                    {{ domain['domain'] }}
                </div>
            </div>
            {%- endfor -%}
        </div>
    </div></div>
</div>

<script>
    $(function () {
        $('.ui.modal.blacklists').modal({
            onApprove : function() {
                return false;
            }
        }).modal('attach events', '.button.blacklists', 'show');

        $('#create_blacklist').form({
            fields: {
                domain : 'empty',
            }
        });

        $('#create_blacklist').api({
            action: 'create blacklist',
            method: 'POST',
            serializeForm: true,
            onSuccess: function() {
                $('#create_blacklist').trigger('reset');
                $('.ui.modal.blacklists').modal('hide');
                $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Domain blacklisted!{{ footer|safe }}');
                $('#tab_blacklist').click();
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
            onError: function() {
                return false;
            },
        });

        $('.delete_domain').api({
            action: 'delete blacklist',
            method: 'DELETE',
            serializeForm: true,
            onSuccess: function() {
                $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Domain blacklist removed!{{ footer|safe }}');
                $('#tab_blacklist').click()
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
            onError: function(errorMessage) {
                $('div.a_message').html('{{ error_header|safe }} Error{{ title_content|safe }}' + errorMessage + '{{ footer|safe }}');
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
        });
    });
</script>

<div class="ui modal blacklists">
    <div class="header">
        Create new blacklist
    </div>
    <div class="content">
        <p>
            {{ render_form(blacklist_form, "create_blacklist") }}
        </p>
    </div>
    <div class="actions">
        <input type="submit" value="Create" form="create_blacklist" class="ui positive button" formmethod="post">
        <div class="ui button cancel">Cancel</div>
    </div>
</div>

app/flask_app/templates/callbacks.html
{%- from "_formhelper.html" import render_form, success_header, error_header, title_content, footer -%}
<button class="ui basic button callbacks">
    <i class="icon code"></i>
    New callback
</button>
<table class="ui celled sortable teal table">
<thead>
    <tr>
    <th>ID</th>
    <th>Hits</th>
    <th>Callback</th>
    </tr>
</thead>
<tbody>
    {%- for row in callbacks -%}
        {% if row['hits'] == 0 %}
        <tr class="negative">
        {% else %}
        <tr>
        {% endif %}
            <td>
                {{ row['id'] }}
            </td>
            <td>
                {{ row['hits'] }}
            </td>
            <td>
                <i class="icon link trash delete_cb" data-id="{{ row['id'] }}"></i>
                {{ row['name'] }}
            </td>
        </tr>
    {%- endfor -%}
</tbody>
</table>

<script>
    $(function () {
        $('.ui.modal.callbacks').modal({
            onApprove : function() {
                return false;
            }
        }).modal('attach events', '.button.callbacks', 'show');

        $('#create_callback').form({
            fields: {
                callback : {
                    rules: [
                        {
                            type   : 'contains[$h]',
                            prompt : 'You must include a location for the host ($h)'
                        },
                        {
                            type   : 'contains[$cb]',
                            prompt : 'You must include a location for the callback ($cb)'
                        },
                        {
                            type   : 'contains[$a]',
                            prompt : 'You must include a location for the assessment ($a)'
                        },
                    ]
                },
            },
        });

        $('#create_callback').api({
            action: 'create callback',
            method: 'POST',
            serializeForm: true,
            onSuccess: function() {
                $('#create_callback').trigger('reset');
                $('.ui.modal.callbacks').modal('hide');
                $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Callback created!{{ footer|safe }}');
                $('#tab_callbacks').click()
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
            onError: function() {
                return false;
            },
        });

        $('.delete_cb').api({
            action: 'delete callback',
            method: 'DELETE',
            serializeForm: true,
            onSuccess: function() {
                $('div.a_message').html('{{ success_header|safe }}Success{{ title_content|safe }}Callback deleted!{{ footer|safe }}');
                $('#tab_callbacks').click()
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
            onError: function(errorMessage) {
                $('div.a_message').html('{{ error_header|safe }} Error{{ title_content|safe }}' + errorMessage + '{{ footer|safe }}');
                $('.message .close').on('click', function() {
                    $(this).closest('.message').transition('fade');
                });
            },
        });
    });
</script>

<div class="ui modal callbacks">
    <div class="header">
        Create new callback
    </div>
    <div class="content">
        <p>
            {{ render_form(callback_form, "create_callback") }}
        </p>
    </div>
    <div class="actions">
        <input type="submit" value="Create" form="create_callback" class="ui positive button" id="btn_create_callback" formmethod="post">
        <div class="ui button cancel">Cancel</div>
    </div>
</div>

app/flask_app/templates/config.html
{%- from "_formhelper.html" import render_form, success_header, error_header, title_content, footer -%}
CONFIG TAB

{#
<button class="ui basic button callbacks">
    <i class="icon code"></i>
    New callback
</button>
<table class="ui celled table">
<thead>
    <tr>
    <th>ID</th>
    <th>Hits</th>
    <th>Callback</th>
    </tr>
</thead>
<tbody>
    <tr>
        <td>No Name Specified</td>
        <td>Unknown</td>
        <td class="negative">None</td>
    </tr>
    <tr class="positive">
        <td>Jimmy</td>
        <td><i class="icon checkmark"></i> Approved</td>
        <td>None</td>
    </tr>
    <tr>
        <td>Jamie</td>
        <td>Unknown</td>
        <td class="positive"><i class="icon close"></i> Requires call</td>
    </tr>
    <tr class="negative">
        <td>Jill</td>
        <td>Unknown</td>
        <td>None</td>
    </tr>
</tbody>
</table>

<script>
    $(function () {
        $('.ui.modal.callbacks').modal({
            onApprove : function() {
                return false;
            }
        }).modal('attach events', '.button.callbacks', 'show');

        $('#create_callback').form({
            fields: {
                callback : {
                    rules: [
                        {
                            type   : 'regExp[/^[a-z0-9_-]{4,16}$/]',
                            prompt : 'Special regex'
                        },
                    ]
                },
            }
        });
    });
</script>

<div class="ui modal callbacks">
    <div class="header">
        Create new callback
    </div>
    <div class="content">
        <p>
            {{ render_form(callback_form, "create_callback") }}
        </p>
    </div>
    <div class="actions">
        <input type="submit" value="Create" form="create_callback" class="ui positive button" formmethod="post">
        <div class="ui button cancel">Cancel</div>
    </div>
</div>
#}

app/flask_app/templates/edit_assessment.html
{%- from "_formhelper.html" import render_form -%}
<div class="ui modal edit_assessment" id="edit_assessment_modal">
    <div class="header">
        Edit assessment
    </div>
    <div class="content">
        <p>
            {{ render_form(edit_assessment_form, "edit_assessment") }}
        </p>
    </div>
    <div class="actions">
        <input type="submit" value="Update" form="edit_assessment" class="ui positive button" id="btn_edit_assessment" formmethod="post" data-action="modify assessment" data-id="">
        <div class="ui button cancel">Cancel</div>
    </div>
</div>

app/flask_app/templates/edit_user.html
{%- from "_formhelper.html" import render_form -%}
<div class="ui modal edit_user">
    <div class="header">
        Edit user
    </div>
    <div class="content">
        <p>
            {{ render_form(edit_user_form, "edit_user") }}
        </p>
    </div>
    <div class="actions">
        <input type="submit" value="Update" form="edit_user" class="ui positive button" id="btn_edit_user" formmethod="post">
        <div class="ui button cancel">Cancel</div>
    </div>
</div>